apiVersion: v1
kind: Service
metadata:
  name: friday-dashboard
  namespace: friday-dashboard
spec:
  selector:
    app: friday-dashboard
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
